// Generated by CoffeeScript 1.10.0
(function() {
  var Blueprint;

  Blueprint = require('../../');

  module.exports = new Blueprint.Model('owners', function() {
    return this.findPetWithName = function(name) {
      return require('./pet').FindOne({
        'name': name
      });
    };
  });

}).call(this);
